version: '3.7'
services:
  prometheus:
    image: prom/prometheus:v2.44.0
    # network_mode: host
    container_name: prometheus
    ports:
      - 9190:9190
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    # command:
    #   - '--config.file=/etc/prometheus/prometheus.yml'

  # grafana:
  #   image: grafana/grafana:9.5.2
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   restart: unless-stopped
  #   volumes:
  #     - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources