version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.44.0
    # network_mode: host
    container_name: prometheus
    restart: always
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    # restart: unless-stopped
    # volumes:
    #   - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources